apiVersion: apps/v1
kind: Deployment
metadata:
  name: #{serviceName}#
spec:
  selector:
    matchLabels:
      app: #{serviceName}#
  replicas: 1
  strategy:
    type: RollingUpdate
  progressDeadlineSeconds: 60
  minReadySeconds: 30
  template:
    metadata:
      labels:
        app: #{serviceName}#
    spec:
      containers:
        - name: #{serviceName}#
          image: #{dockerRepository}##{imageName}#:#{imageTagName}#
          imagePullPolicy: Always
      imagePullSecrets:
        - name: nexuscredentials
---
kind: Service
apiVersion: v1
metadata:
  name: #{serviceName}#
  labels:
    app: #{serviceName}#
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: #{serviceName}#
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: #{serviceName}#
  labels:
    app: #{serviceName}#
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: #{host}#
      http:
        paths:
          - path: #{urlPath}#(/|$)(.*)
            backend:
              serviceName: #{serviceName}#
              servicePort: 80
