pipeline {
    environment {
        DOCKER_REPOSITORY_PUSH = "nxs.tribanco.com.br:8082/"
		DOCKER_REPOSITORY_PULL = "nxs.tribanco.com.br:8181/"
        IMAGE_NAME = "${SERVICE_NAME}"
        URL_PATH = "/${SERVICE_NAME}"
    }
    agent {label 'docker-agent'}
    stages {
		stage('Publish to Cluster') {
            steps {
                script{
                    echo "${IMAGE_TAG_NAME}"
                    def fileContent = readFile('deploy/deployment.yaml')
                    fileContent = fileContent.replace('#{serviceName}#', "${SERVICE_NAME}")
                    fileContent = fileContent.replace('#{dockerRepository}#', "${DOCKER_REPOSITORY_PULL}")
                    fileContent = fileContent.replace('#{imageName}#', "${IMAGE_NAME}")
                    fileContent = fileContent.replace('#{imageTagName}#', "${IMAGE_TAG_NAME}")
                    fileContent = fileContent.replace('#{host}#', "${HOST_ADDRESS}")
                    fileContent = fileContent.replace('#{urlPath}#', "${URL_PATH}")

                    echo fileContent;
                    writeFile(file: 'deploy/deployment-Version.yaml', text: fileContent)
                }

                sh 'kubectl -n pj apply -f deploy/deployment-Version.yaml'
                //sh "helm upgrade --install --force --set name=poc-ciandt.back-api --set image.tag=dev  poc-ciandt.back-api ./deploy/helm/poc-ciandt-back-api"
            }
        }
	}
}