export const SCREEN_SENDDOC_INTRO = 'SCREEN_SENDDOC_INTRO'

export const SCREEN_SENDDOC_PRINT_FRONT = 'SCREEN_SENDDOC_PRINT_FRONT'
export const SCREEN_SENDDOC_CONFIRM_FRONT = 'SCREEN_SENDDOC_CONFIRM_FRONT'

export const SCREEN_SENDDOC_PRINT_BACK = 'SCREEN_SENDDOC_PRINT_BACK'
export const SCREEN_SENDDOC_CONFIRM_BACK = 'SCREEN_SENDDOC_CONFIRM_BACK'

export const SCREEN_SENDDOC_FEEDBACK_SUCCESS = 'SCREEN_SENDDOC_FEEDBACK_SUCCESS'
export const SCREEN_SENDDOC_FEEDBACK_ERROR = 'SCREEN_SENDDOC_FEEDBACK_ERROR'

export const SCREEN_SENDDOC_DOCS_NEED = 'SCREEN_SENDDOC_DOCS_NEED'